name: llpatcolliders
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.26,<2.0
  - pandas>=2.2,<3.0
  - matplotlib>=3.8,<4.0
  - scipy>=1.12,<2.0
  - shapely>=2.0,<3.0
  - tqdm>=4.66,<5.0
  - jupyter>=1.0,<2.0
  - notebook>=7.1,<8.0
  - rtree>=1.0,<2.0
  - pip
  - pip:
    - trimesh>=4.1.7,<5.0
