name: llpatcolliders
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.8.*
  - scipy=1.12.*
  - shapely=2.0.*
  - tqdm=4.66.*
  - jupyter=1.0.*
  - notebook=7.1.*
  - rtree>=1.0
  - pip
  - pip:
    - trimesh==4.1.7  # Install via pip for better availability
